# Generated by Django 4.2.30 on 2026-08-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courses',
            table='courses',
        ),
    ]
